title: Vtor's Blog
description: >- 
  A collection of things to learn and teach.
  <br/>Mostly game development and programming.
twitter_username: Vtor_
plugins:
  - jekyll-remote-theme

remote_theme: fongandrew/hydeout
paginate: 5
